alias la='ls -A'
alias l='ls -CF'
alias less='less -iMRX'
alias ll='ls -lFhp --color --time-style="+%Y-%m-%d %H:%M"'
alias jalang='export LANG=ja_JP.utf8'
alias enlang='export LANG=en_us.utf8'
alias df='df -H'
alias free='free -h'